import { NextRequest, NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";
import type { PageAuditData } from "../audit/route";

function buildPrompt(urls: string[], auditData: PageAuditData[]): string {
  const avgScore = auditData.reduce((s, p) => s + p.score, 0) / auditData.length;
  const critical = auditData.filter(p => p.score < 40);
  const warnings = auditData.filter(p => p.score >= 40 && p.score < 70);
  const good = auditData.filter(p => p.score >= 70);
  const missingTitles = auditData.filter(p => !p.title);
  const missingDesc = auditData.filter(p => !p.description);
  const noH1 = auditData.filter(p => p.h1Count === 0);
  const slowPages = auditData.filter(p => p.loadTimeMs > 3000);
  const brokenPages = auditData.filter(p => p.statusCode >= 400);

  const topIssues = auditData
    .sort((a, b) => a.score - b.score)
    .slice(0, 10)
    .map(p => `  - ${p.url} | Score: ${p.score} | Load: ${p.loadTimeMs}ms | H1s: ${p.h1Count} | Title: ${p.title || "MISSING"}`);

  return `You are a senior SEO consultant. Generate a complete, professional HTML+CSS SEO audit report for a client.

AUDIT DATA SUMMARY:
- Sites audited: ${urls.join(", ")}
- Total pages: ${auditData.length}
- Average SEO score: ${avgScore.toFixed(1)}/100
- Critical pages (score < 40): ${critical.length}
- Warning pages (score 40–70): ${warnings.length}
- Good pages (score ≥ 70): ${good.length}
- Missing title tags: ${missingTitles.length}
- Missing meta descriptions: ${missingDesc.length}
- Pages with no H1: ${noH1.length}
- Slow pages (>3s load): ${slowPages.length}
- Broken pages (4xx/5xx): ${brokenPages.length}

TOP ISSUES (worst pages):
${topIssues.join("\n")}

ALL PAGES DATA (JSON):
${JSON.stringify(auditData.slice(0, 30), null, 2)}

REQUIREMENTS FOR THE HTML REPORT:
1. Professional dark-themed design (dark navy/slate background, white text, accent colors: violet #7c3aed, emerald #10b981, amber #f59e0b, red #ef4444)
2. Include a prominent header with logo area, report title, date, and domains audited
3. Executive summary section with key stats in large bold cards (total pages, avg score, critical issues count)
4. A visual score breakdown — use CSS bar charts or circles to show score distribution
5. Issues breakdown table: list every page with columns: URL, Score, Title, H1, Load Time, Status — use color coding (red/amber/green rows based on score)
6. Recommendations section: top 5 prioritised fixes with clear action items
7. Footer with "Generated by SEO Audit Tool" and date
8. Use only inline CSS and no external dependencies — the PDF must be self-contained
9. Use Google Fonts via @import for typography (Inter)
10. Make it look like a premium agency deliverable — clean spacing, subtle gradients, good hierarchy
11. Tables should have alternating row colors and sticky headers
12. Include a page for each domain if multiple were audited

Return ONLY the complete HTML document, starting with <!DOCTYPE html>. No markdown, no explanation, just HTML.`;
}

export async function POST(req: NextRequest) {
  try {
    const { auditData, urls, anthropicKey } = await req.json();
    if (!auditData?.length || !anthropicKey) {
      return NextResponse.json({ error: "Missing auditData or anthropicKey" }, { status: 400 });
    }

    const client = new Anthropic({ apiKey: anthropicKey });
    const prompt = buildPrompt(urls, auditData);

    const msg = await client.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 8192,
      messages: [{ role: "user", content: prompt }],
    });

    const html = (msg.content[0] as { text: string }).text.trim();
    if (!html.startsWith("<!DOCTYPE")) {
      throw new Error("Claude returned unexpected content");
    }

    return NextResponse.json({ html });
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : "Report generation error";
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
